### ISSUE TITLE
What does mimic Guice annotation bindings for the same class?

### ISSUE THREAD

**Issue by basilmusa** [illuin-tech/opyoid#21]
Interested to know what does mimic Guice annotation bindings for the same class/interface.

For example I have an interface called `MessageSendingService`.

I want to bind `MessageSendingService` to the implementation `TwitterService` when annotated with @TwitterService
I want to bind `MessageSendingService` to the implementation `EmailService` when annotated with @EmailService

I know annotations don't exist in python, so what would be the alternative here and in Opyoid?

**Comment by Aegdesil** [comment]
The equivalent in Opyoid is named arguments, you can read more about its usage here: https://github.com/illuin-tech/opyoid/blob/master/docs/names.md
