### ISSUE TITLE
MultiBinding using providers fails due to caching in callable_to_provider_adapter

### ISSUE THREAD

**Issue by ardjanzwartjes** [illuin-tech/opyoid#69]
I've come across a bug involving multi binding, this bug is present in versions 1.7.0 and 2.0.0 (I haven't tried other versions). Below is an example demonstration reduced to the simplest form:

```
from opyoid import Module, Injector
from typing import List

class MultiModule(Module):
    def __init__(self):
        super().__init__()

    def configure(self) -> None:
        self.multi_bind(str, [self.bind_item(to_provider=self.provider1), self.bind_item(to_provider=self.provider2)], override_bindings=False)

    def provider1(self):
        return "One"

    def provider2(self):
        return "Two"

injector=Injector([MultiModule()])
result=injector.inject(List[str])
print(result)
```

Naturally, the expected output is ['One', 'Two']. In reality, the output is ['One', 'One']. 

Adding the line `self.bind(str, to_instance="Three")` to the configure method changes the output to ['Three', 'Three'].

The problem seems to be that in the injection context for these providers, it is not known that the provider is for a specific item in a multi_binding. Line 27 (version 2.0.0) of callable_to_provider_adapter.py looks for just a provider for type str, resulting in either the first, or the global str provider, which does not seem to be the desired behaviour.

As a workaround I now give each bind_item a unique named argument, which leads to the desired output of ['One', 'Two'].

**Comment by Aegdesil** [comment]
Indeed, this is a limitation of the MultiBinding, I'll look into implementing a fix for this.

**Comment by ardjanzwartjes** [comment]
Thanks. My workaround is changing `self.bind_item(to_provider=self.provider1)` into `self.bind_item(to_provider=self.provider1, named=f"{uuid4()}")`. Not pretty, but it gets the job done.
